web/router.ex
defmodule Nermesterts.Router do
  use Nermesterts.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :edit_authenticate do
    plug Nermesterts.Plug.EditAuthenticate
  end

  pipeline :view_authenticate do
    plug Nermesterts.Plug.ViewAuthenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Nermesterts do
    pipe_through :browser

    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/login", SessionController, only: [:new, :create]
  end

  scope "/", Nermesterts do
    pipe_through [:browser, :view_authenticate]

    get "/", PageController, :index
    get "/games", GameController, :index
    get "/phrases", PhraseController, :index
  end

  scope "/", Nermesterts do
    pipe_through [:browser, :edit_authenticate] # Use the default browser stack

    post "/", PageController, :post

    delete "/logout", SessionController, :delete

    resources "/user", UserController, only: [:edit, :update, :delete]

    post "/players/guest", PlayerController, :add_guest, as: :add_guest
    put "/players/deactivate", PlayerController, :deactivate_all, as: :player_deactivate_all
    resources "/players", PlayerController, except: [:new, :create, :show] do
      put "/activate", PlayerController, :activate, as: :activate
      put "/deactivate", PlayerController, :deactivate, as: :deactivate
    end

    get "/games/search", GameController, :search, as: :game_search
    resources "/games", GameController, except: [:edit, :index, :update]
    resources "/phrases", PhraseController, except: [:index]
  end

  # Other scopes may use custom stacks.
  scope "/api", Nermesterts do
    pipe_through :api

    get "/game", PageController, :index
  end
end

web/models/user.ex
defmodule Nermesterts.User do
  use Nermesterts.Web, :model

  alias Nermesterts.User

  @required_fields ~w(username)a
  @optional_fields ~w(active admin bgg_username guest name password password_confirmation)a
  @all_fields @required_fields ++ @optional_fields

  @required_registration_fields ~w(username password password_confirmation)a
  @all_registration_fields @required_registration_fields ++ @optional_fields

  @guest_creation_fields ~w(crypted_password)a ++ @all_fields

  schema "users" do
    field :username, :string
    field :bgg_username, :string
    field :crypted_password, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    field :name, :string
    field :active, :boolean, default: false
    field :guest, :boolean, default: false
    field :admin, :boolean, default: false

    many_to_many :games, Nermesterts.Game, join_through: "user_games",
      join_keys: [user_id: :id, game_id: :bgg_id], unique: true,
      on_replace: :delete

    timestamps()
  end

  def guest_changeset() do
    uuid = UUID.uuid4(:hex)
    guest_value = "guest-#{uuid}"
    params = %{name: "Guest", username: String.slice(guest_value, 0..19),
      crypted_password: guest_value, active: true, guest: true}
    cast(%User{}, params, @guest_creation_fields)
  end

  def registration_changeset(struct, params) do
    struct
    |> cast(params, @all_registration_fields)
    |> validate_required(@required_registration_fields)
    |> common_changeset
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @all_fields)
    |> validate_required(@required_fields)
    |> common_changeset
  end

  defp common_changeset(changeset) do
    changeset
    |> validate_length(:username, min: 3, max: 20)
    |> unique_constraint(:username, downcase: true)
    |> unique_constraint(:unique_user_games_index)
    |> validate_length(:password, min: 6)
    |> validate_confirmation(:password)
    |> put_encrypted_pass
  end

  def display_name(user) do
    display_name(user.username, user.name)
  end
  defp display_name(_, name) when not is_nil(name) do
    name
  end
  defp display_name(username, _) do
    username
  end

  @doc """
  Creates a query that orders users by name.
  """
  def ordered(query) do
    from u in query,
      order_by: u.name
  end

  @doc """
  Returns a query that gets all users whose active flag matches the passed in value.
  """
  def active(query, active) do
    from u in query,
      where: u.active == ^active and u.guest == false
  end

  @doc """
  Returns a query that gets all guest users
  """
  def guest(query) do
    from u in query,
      where: u.guest == true
  end

  defp put_encrypted_pass(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :crypted_password, Comeonin.Bcrypt.hashpwsalt(pass))
      _ ->
        changeset
    end
  end
end

web/controllers/user_controller.ex
defmodule Nermesterts.UserController do
  use Nermesterts.Web, :controller
  alias Nermesterts.User
  import Nermesterts.ControllerHelpers

  plug :load_and_authorize_resource, model: User

  def edit(conn, _params) do
    if conn.assigns.authorized do
      user = conn.assigns.user
      changeset = User.changeset(user)
      render(conn, "edit.html", user: user, changeset: changeset)
    else
      redirect_not_authorized(conn, page_path(conn, :index))
    end
  end

  def update(conn, %{"user" => user_params}) do
    if conn.assigns.authorized do
      user = conn.assigns.user
      changeset = User.changeset(user, user_params)

      case Repo.update(changeset) do
        {:ok, _user} ->
          conn
          |> put_flash(:info, "User updated successfully.")
          |> redirect(to: page_path(conn, :index))
        {:error, changeset} ->
          render(conn, "edit.html", user: user, changeset: changeset)
      end
    else
      redirect_not_authorized(conn, page_path(conn, :index))
    end
  end

  def delete(conn, _params) do
    if conn.assigns.authorized do
      user = conn.assigns.user

      # Here we use delete! (with a bang) because we expect
      # it to always work (and if it does not, it will raise).
      Repo.delete!(user)

      conn
      |> put_flash(:info, "User deleted successfully.")
      |> redirect(to: page_path(conn, :index))
    else
      redirect_not_authorized(conn, page_path(conn, :index))
    end
  end
end

web/views/user_view.ex
defmodule Nermesterts.UserView do
  use Nermesterts.Web, :view
end

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: page_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :name, "Display Name", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :bgg_username, "BGG Username", class: "control-label" %>
    <%= text_input f, :bgg_username, class: "form-control" %>
    <%= error_tag f, :bgg_username %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, "Password Confirmation", class: "control-label" %>
    <%= password_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Active players (<%= length(@active_players) %>):</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for user <- @active_players do %>
    <tr>
      <td><%= sanitize(User.display_name(user)) %></td>

      <td class="text-right">
        <%= if logged_in?(@conn) do %>
          <%= link "Deactivate", to: player_deactivate_path(@conn, :deactivate, user), method: :put, class: "btn btn-default btn-xs" %>
          <%= if not user.guest and (is_admin?(@conn) or user.id == current_user(@conn).id) do %>
            <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
            <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, class: "btn btn-danger btn-xs",
                  data: [confirm: "Are you sure you want to delete #{User.display_name(user)}?"] %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= if logged_in?(@conn) do %>
  <%= link "Add Guest", to: add_guest_path(@conn, :add_guest), method: :post, class: "btn btn-default btn-xs" %>
  <%= link "Clear", to: player_deactivate_all_path(@conn, :deactivate_all), method: :put, class: "btn btn-default btn-xs" %>
<% end %>

<h2>Inactive players (<%= length(@inactive_players) %>):</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @inactive_players do %>
    <tr>
      <td><%= sanitize(User.display_name(user)) %></td>

      <td class="text-right">
        <%= if logged_in?(@conn) do %>
          <%= link "Activate", to: player_activate_path(@conn, :activate, user), method: :put, class: "btn btn-default btn-xs" %>
          <%= if is_admin?(@conn) or user.id == current_user(@conn).id do %>
            <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
            <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, class: "btn btn-danger btn-xs",
                  data: [confirm: "Are you sure you want to delete #{User.display_name(user)}?"] %>
          <% end %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>