web/router.ex
defmodule Nermesterts.Router do
  use Nermesterts.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :edit_authenticate do
    plug Nermesterts.Plug.EditAuthenticate
  end

  pipeline :view_authenticate do
    plug Nermesterts.Plug.ViewAuthenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Nermesterts do
    pipe_through :browser

    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/login", SessionController, only: [:new, :create]
  end

  scope "/", Nermesterts do
    pipe_through [:browser, :view_authenticate]

    get "/", PageController, :index
    get "/games", GameController, :index
    get "/phrases", PhraseController, :index
  end

  scope "/", Nermesterts do
    pipe_through [:browser, :edit_authenticate] # Use the default browser stack

    post "/", PageController, :post

    delete "/logout", SessionController, :delete

    resources "/user", UserController, only: [:edit, :update, :delete]

    post "/players/guest", PlayerController, :add_guest, as: :add_guest
    put "/players/deactivate", PlayerController, :deactivate_all, as: :player_deactivate_all
    resources "/players", PlayerController, except: [:new, :create, :show] do
      put "/activate", PlayerController, :activate, as: :activate
      put "/deactivate", PlayerController, :deactivate, as: :deactivate
    end

    get "/games/search", GameController, :search, as: :game_search
    resources "/games", GameController, except: [:edit, :index, :update]
    resources "/phrases", PhraseController, except: [:index]
  end

  # Other scopes may use custom stacks.
  scope "/api", Nermesterts do
    pipe_through :api

    get "/game", PageController, :index
  end
end

web/views/layout_view.ex
defmodule Nermesterts.LayoutView do
  use Nermesterts.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CoverMyTabletop</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav role="navigation" class="navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <%= link "", to: page_path(@conn, :index), class: "logo navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav nav-pills navbar-right">
            <li role="presentation"><%= link "Home", to: page_path(@conn, :index)%></li>
            <li role="presentation"><%= link "Phrases", to: phrase_path(@conn, :index)%></li>
            <li role="presentation"><%= link "Games", to: game_path(@conn, :index)%></li>
            <li class="dropdown" role="presentation">
            <a href="#" class="dropdown-toggle" data-html="true" data-toggle="dropdown"> <%= sanitize(current_user_name(@conn)) %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <%= if logged_in?(@conn) do %>
                  <li><%= link "Edit", to: user_path(@conn, :edit, current_user(@conn))%></li>
                  <li><%= link "Log Out", to: session_path(@conn, :delete), method: "delete" %></li>
                <% else %>
                  <li><%= link "Log In", to: session_path(@conn, :new) %></li>
                  <li><%= link "Register", to: registration_path(@conn, :new) %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container paneled">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
  </body>
</html>